---
- name: install apache2
  hosts: all  
  become: yes  

  vars:
    port: 8080

  tasks:
    - name: install apache2 in slave
      apt:
        name: apache2
        state: present

    - name: start apache2	
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Backup Apache2 default ports config
      copy:
        src: /etc/apache2/ports.conf
        dest: /etc/apache2/ports.conf.bak
        remote_src: yes

    - name: Deploy configuration file
      template:
        src: /root/ports.conf.j2  
        dest: /etc/apache2/ports.conf 
      notify:
        - Restart apache2

  handlers:
    - name: Restart apache2
      service:
        name: apache2
        state: restarted

